#!/bin/bash
#(()) - subshell, run in the background
# $#- number of arguments passed in the script

if [ $# -ne 1 ]
then
    echo "This script requires exactly an argument passed into it."
    echo "Please enter an argument."
    exit 1
fi

lines=$(ls -lh $1 | wc -l)

echo "You have $(($lines-1)) objects in the $1 directory"
