#!/bin/bash

#Check to make sure the user has entered exactly two arguments.
if [ #? -ne 2 ]
    echo "Usage: backup.sh <source_directory> <target_directory>"
    echo "Please try again."
    exit 1
fi

#Check to see if rsync is not installed and install it
#command -v is used to check the existence and location of a command 

if ! command -v rsync > /dev/null 2>&1
then
    echo "This script requires rsync to installed."
    sudo apt update 
    sudo apt install -y rsync
fi

#Capture the current date, and store it in this format: YYYY-MM-DD
current_date=$(date +%Y-%m-%d)

rsync_options="-avb --backup-dir $2/$current_date --delete --dry-run"

$(which rsync) $rsync_options $1 $2/current >> backup_$current_date.log
