#!/bin/bash

#Case selection is used to provide options in a multiple situation for user.

finished=0

while [ $finished -ne 1 ]
do
    echo "Enter a number"

    echo "1 - One" 
    echo "2 - Two" 
    echo "3 - Three" 
    echo "4 - Four" 
    echo "5 - Five"
    echo "6 - Exit Script" 

    read distro;

   case $distro in
       1) echo "You've entered one. ";;
       2) echo "You've entered two. ";;
       3) echo "You've entered three. ";;
       4) echo "You've entered four. ";;
       5) echo "You've entered five. ";;
       6) finished=1  ;;
       *) echo "You've entered an incorrect option"
   esac
done

echo "Thank you"

