#!/bin/bash

#Functions are used to repeat codes.

release_file=/etc/os-release
logfile=~/Boring_Stuff/Bash/logFiles/updater.log
errorlog=~/Boring_Stuff/Bash/logFiles/updater_errors.log

check_exit_status() {
    if [ $? -ne 0 ]
    then 
        echo "An error occured, please check the $errorlog file."
    fi
}
if grep -q "arch" $release_file
then
    # For host on Arch 
    sudo pacman -Syu >>$logfile 2>>$errorlog
    check_exit_status

elif grep -q "debian" $release_file || grep -q "ubuntu" $release_file
then
    # For Debian or Ubuntu host
    sudo apt update  >>$logfile 2>>$errorlog
    check_exit_status

    sudo apt dist-upgrade -y >>$logfile 2>>$errorlog
    check_exit_status
else
    echo "No host found"
fi
