#!/bin/bash

commit_message=$(date +%d/%m/%Y)
diff=$(git diff)
runtime=~/Boring_Stuff/Bash/Logfiles/Runtimes/"$0_runtime"
git_result=~/Boring_Stuff/Bash/Logfiles/Results/"$0_results"
git_error=~/Boring_Stuff/Bash/Logfiles/Errors/"$0_errors"

"$diff"
git_function(){
git init
git add --all
git commit -m "$commit_message"
git push
}
if [[ -z "$diff" ]];
then
    echo "No changes detected" >$git_error
    exit 0
else
    git_function >$git_result
    echo "$0 script ran at $(date)" >>$runtime
fi
echo "Changes pushed"
