#!/bin/bash

myNum=300

#which is used to find if an app exists in linux.
# -f or -d to check for file
# ! means not true
# -ne means not equal
# -gt means >> or greater than
# -lt means << or less than
# -eg means equal to
if [ $myNum -eq 200 ]
then
    echo "The condition is true."
else
    echo "The condition is false."
fi

